version: '3'

services:
  nginx:
    build: 
      context: ./nginx
    image: guischafer/desafionodejs-nginx:prod  
    container_name: nginx  
    networks:
      - desafio-nodejs
    ports:
      - "8080:80"
  app:
    build: 
      context: ./nodejs
    image: guischafer/desafionodejs-nodeapp:prod  
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    networks:
      - desafio-nodejs
    tty: true
    depends_on: 
      - db
    
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name:  db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql 
    environment:
      - MYSQL_DATABASE=desafionodejs
      - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_USER=root
    networks:
      - desafio-nodejs

networks:
  desafio-nodejs:
    driver: bridge